### ISSUE TITLE
file name and structure convention

### ISSUE THREAD

**Issue by inpercima** [inpercima/run-and-fun#25]
There exists a lot of style guides like:
https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub or http://www.johnpapa.net/angular-app-structuring-guidelines/.

I would use a mixture of several guidelines. Let us discuss about this.

**Comment by inpercima** [comment]
Before I commit some changes into the specifed branch, here the first idea of the structure:

public
|-- css/
|-- js/
|   |-- config/
|   |   |-- app.log.config.js
|   |   |-- app.route.config.js
|   |-- feature/
|   |   |-- activity/
|   |   |   |-- activity.controller.js
|   |   |   |-- activity.service.js
|   |   |-- login/
|   |   |   |-- login.controller.js
|   |   |   |-- login.service.js
|   |-- directive/
|   |-- util/
|   |-- app.js

**Comment by sepe81** [comment]
The additional subfolders seem to be a bit overloaded for the size of our app. Maybe we can discuss it on monday?

**Comment by inpercima** [comment]
Maybe for the moment ;) We should discuss this.

**Comment by inpercima** [comment]
We do not change the structure for the moment.
