### ISSUE TITLE
application default configuration

### ISSUE THREAD

**Issue by sepe81** [inpercima/run-and-fun#29]
spring boot provides various options for environment specific configuration

see: http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by sepe81** [comment]
With spring boot 1.3.0 we can rename `application.properties.default` to `application-default.properties`. After this we just need to overwrite the individual keys per instance.

> if no profiles are explicitly activated then properties from application-default.properties are loaded

**Comment by inpercima** [comment]
Sounds good. We just need to update, right?

**Comment by inpercima** [comment]
See https://github.com/inpercima/run-and-fun/pull/34
