### ISSUE TITLE
Fetch only new activities from runkeeper

### ISSUE THREAD

**Issue by sepe81** [inpercima/run-and-fun#5]
After login to runkeeper it's possible to index all activities through the given rest api. Every activity gets dowloaded and inserted/updated into elasticsearch (ES). It would be better to fetch only new activities after the first indexing has taken place.

**Comment by inpercima** [comment]
Can be closed, right?

**Comment by inpercima** [comment]
I think we should open a new issue for the other things like `every time one new activity is loaded` but there is no one.
