### ISSUE TITLE
pie chart will not load every time

### ISSUE THREAD

**Issue by inpercima** [inpercima/run-and-fun#56]
It seems that the pie chart will not load correct if the internet connect is not stable enough. Sitting in the train with hotspot it loads the graphic either not or not completely.
![chart](https://cloud.githubusercontent.com/assets/10551931/14403331/0d7ef82e-fe53-11e5-9181-634da654a26d.png)

**Comment by inpercima** [comment]
It looks as if this is not the becaus of the Internet connection. Seems it comes by updates of dependencies.

**Comment by inpercima** [comment]
@sepe81 Will you check if this depends on the version problem?

**Comment by sepe81** [comment]
Actually I checked the problem using chrome network throttling (simulating GPRS). It took some time to load but it worked! ;-)

Great tool -- see http://stackoverflow.com/questions/3536249/simulating-slow-internet-connection

**Comment by inpercima** [comment]
I tested it now and it seems to work. I think this really was an problem of the wrong version. The chart wasn't loading also with good network connection.
