### ISSUE TITLE
xmlRequestProvider preventing karma from running

### ISSUE THREAD

**Issue by CMRHDL** [inpercima/run-and-fun#86]
Hey, what exactly is [xmlRequestProvider](https://github.com/inpercima/run-and-fun/blob/master/src/main/resources/public/js/log.config.js#L7-L8)? Cant find infos about that anywhere.

Error: `TypeError: Cannot read property 'debug' of undefined`

**Comment by inpercima** [comment]
Hey, in the file config.json you can enable debug. Normally this file exists.

**Comment by CMRHDL** [comment]
Thanks.
Could you provide some spec or reference for that? Where is that module coming from?

**Comment by inpercima** [comment]
It is defined in xmlRequest.provider.js and is used to read the config file. At the beginning I wanted to activate the logging. Later was also changing the loglevel by calling the url like `debug=false` or so. This I have not followed up.
