### ISSUE TITLE
Upgrade spring-boot to 1.5.x

### ISSUE THREAD

**Issue by sepe81** [inpercima/run-and-fun#94]
At the moment we use spring-boot 1.4.6. When updating to 1.5.3 there is an exception when calling `findAllByTypeOrderByDateDesc`

```
10:34:50.689 INFO  n.i.r.service.RunAndFunServiceImpl:196 - {
  "bool" : {
    "must" : {
      "bool" : {
        "should" : {
          "term" : {
            "type" : "running"
          }
        }
      }
    }
  }
}
10:34:51.003 WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver:407 - Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON document: (was java.lang.NullPointerException) (through reference chain: org.springframework.data.elasticsearch.core.aggregation.impl.AggregatedPageImpl["facets"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.springframework.data.elasticsearch.core.aggregation.impl.AggregatedPageImpl["facets"])
```

**Comment by sepe81** [comment]
Analysis:

spring-boot-1.5.3 includes spring-data-elasticsearch-2.1.3.RELEASE.jar
The problem should be connected to https://github.com/spring-projects/spring-data-elasticsearch/pull/175

**Comment by inpercima** [comment]
Thanks for analysing.

**Comment by sepe81** [comment]
I commented the new status under https://github.com/spring-projects/spring-data-elasticsearch/pull/175

The solution is still not part of spring-data-elasticsearch-2.1.6 and spring-boot 1.5.6 still has the problem.

**Comment by sepe81** [comment]
spring-boot 1.5.7 also doesn't contain the fix for spring-data-elasticsearch

**Comment by darkamenosa** [comment]
spring-boot 1.5.8 doesn't contain the fix too. :(

**Comment by jayrp11** [comment]
spring-boot 1.5.9 doesn't contain the fix too. This issue started with spring-boot 1.5.0.

**Comment by sepe81** [comment]
Superseded by https://github.com/inpercima/run-and-fun/pull/100
